version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webappwithdocker
    build:
      context: .
      dockerfile: WebAppWithDocker/Dockerfile
   
  webclient:
    image: webclient
    build:
      context: ./webclient
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline

