version: '3.4'

services:
  webapi:
    image: tetianash/webapi:latest
    # container_name: webapi
    build:
      context: .
      dockerfile: WebAppWithDocker/Dockerfile
      
  webclient:
    image: tetianash/webclient:latest
    # container_name: webclient
    build:
      context: ./webclient
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline

